### ISSUE TITLE
优化表格列宽

### ISSUE THREAD

**Issue by LZS911** [actiontech/dms#129]
![img_v3_026n_180302b0-a531-44ef-9a2d-5830338981ag](https://github.com/actiontech/dms/assets/42765421/e009a32d-47bc-4faf-84da-e3aaf018d6df)

例如角色列表中角色名列过长，需要设置合适的列宽。
希望能检查下项目其他表格是否也存在该问题。

**Comment by zzyangh** [comment]
目前存在该问题的列表：

- 工作台-待处理工单/我的工单情况
![企业微信截图_17170395583272](https://github.com/actiontech/dms/assets/39512256/677e7903-7203-4593-ac7b-daf90da2b32f)

- 审核规则模板
![企业微信截图_17170397761322](https://github.com/actiontech/dms/assets/39512256/29ac46fd-f6f1-4748-b453-58d2bdc17bd3)

- 白名单
![企业微信截图_17170482273268](https://github.com/actiontech/dms/assets/39512256/8a28d062-7cf4-40e4-bd8c-ea99b20c2961)

- 成员与权限管理
![企业微信截图_17170398169962](https://github.com/actiontech/dms/assets/39512256/f480e240-a29b-4f23-bcfe-2a3f8c5eaa9c)

**Comment by hasa1K** [comment]
### 版本
dms-ui ee:6bc7efb907c9463f3944300933d48043dc108e47

### 验证
#### 修复之后
**用户中心**
![image](https://github.com/actiontech/dms/assets/53266479/244ccff1-92f4-46aa-908d-deced5ccd8a0)

**工作台-待处理工单/我的工单情况**
![image](https://github.com/actiontech/dms/assets/53266479/80b04688-a502-4a83-898c-a4663fc495c2)

**审核规则模板**
![image](https://github.com/actiontech/dms/assets/53266479/f2d326d0-026f-4b0f-bf5f-ee78ba833562)


**成员与权限管理**
![image](https://github.com/actiontech/dms/assets/53266479/91c8d1f1-1558-44f0-8e02-a0f5ed3fcff7)

**白名单**
![image](https://github.com/actiontech/dms/assets/53266479/d3ffb34e-2cf7-4093-a49a-e2d3f11a0699)
