### ISSUE TITLE
bug：删除用户导致打开成员与权限报错

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/dms#136]
## 现象
在用户中心删除在某个项目的成员后，在对应项目中打开成员与权限，报错：
get user failed: dms: storage no data:failed to get user: record not found
## 复现操作
![Screenshot_2024-01-09_10-02-14](https://github.com/actiontech/dms/assets/31072467/8218c560-6385-428b-854d-66b1927b968d)

## 原因
删除了用户之后，没有删除（或软删除）项目中的成员，及其相关记录。
导致在获取项目中的成员列表时，获取到已经删除的用户，导致报错。

**Comment by taolx0** [comment]
UI: main-ee 09c032e4
DMS: main-ee 0f03f1dd12
SQLE: main-ee daee60eff4
![20240201105113](https://github.com/actiontech/dms/assets/63177450/a9f6129d-990a-49be-b928-2006e7d48bc6)
