### ISSUE TITLE
sqle版本对比形态改动

### ISSUE THREAD

**Issue by zzyangh** [actiontech/dms#152]
目前形态：
![image](https://github.com/actiontech/dms/assets/39512256/8711b673-e839-49fe-b554-4e55e45614d1)

改动如下图：
![image](https://github.com/actiontech/dms/assets/39512256/c77c44e7-60bf-42b8-a9da-489e4183a4d9)

- 点击快速部署，跳转用户手册-安装方式说明页 https://actiontech.github.io/sqle-docs/docs/deploy-manual/intro
- 点击立即申请，跳转金数据  https://jinshuju.net/f/daLFaG
- 点击联系我们，跳转用户手册-商业支持页 https://jinshuju.net/f/daLFaG
- 点击功能对比，跳转用户手册功能对比页面 https://actiontech.github.io/sqle-docs/docs/support/compare

**Comment by taolx0** [comment]
UI: main 743412d8
DMS: main-ee 0ab6af242e
SQLE: main-ee 342c635080
![20240131135707](https://github.com/actiontech/dms/assets/63177450/bdb336c4-42fc-41a9-8e8a-e56468d64be0)
