### ISSUE TITLE
配置proxy路由转发规则导致数据源测试连通性失败

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/dms#153]
## 现象描述
点击测试数据源连通性失败
![image](https://github.com/actiontech/dms/assets/31072467/fc08e681-0d8c-4278-937c-50a3283f28e0)
测试数据源连通性的响应体
HTTP Response
``` 
{
    "data": [
        {
            "is_connectable": false,
            "component": "xxxxxx",
            "connect_error_message": "query data error: Post \"http://127.0.0.1:xxxx/v1/internal/db_services/connection\": dial tcp 127.0.0.1:7063: connect: connection refused"
        },
        {
            "is_connectable": false,
            "component": "xxxxx",
            "connect_error_message": "query data error: Post \"http://127.0.0.1:xxxx/v1/internal/db_services/connection\": dial tcp 127.0.0.1:7064: connect: connection refused"
        },
        {
            "is_connectable": false,
            "component": "sqle",
            "connect_error_message": "open plugin: new executor in inspect: Error 1045 (28000): Access denied for user 'test'@'10.186.62.32' (using password: NO)"
        }
    ],
    "code": 0,
    "message": ""
}
```
## 复现方法
1. 数据库中，proxy_targets表配置了两条路由转发的规则
![image](https://github.com/actiontech/dms/assets/31072467/06c21797-8a93-41c3-8119-92318cf67757)
2. 点击测试数据源连通性
## 问题原因
在测试数据源联通性的代码中，加载了proxy_targets表中的所有记录，并且根据这些记录拼接URL，并发请求测试连通性
实际上只要请求到sqle即可，其他的不需要
![img_v3_027f_3c067bc2-be70-4211-abc2-8921a063913g](https://github.com/actiontech/dms/assets/31072467/5ecbd577-0840-4811-bc73-64c090065936)

**Comment by taolx0** [comment]
![image](https://github.com/actiontech/dms/assets/63177450/950055c0-7d6f-49bc-a4dc-46d5fc7a8a6b)
![20240201174248](https://github.com/actiontech/dms/assets/63177450/7a31ce58-3f3d-459c-ac98-966bf7511f61)

**Comment by winfredLIN** [comment]
https://github.com/actiontech/sqle-ee/issues/1367
