### ISSUE TITLE
SQL工作台审核时，预计使用数据源上应用的规则模板，实际使用了该数据源类型对应的默认规则模板

### ISSUE THREAD

**Issue by Gygkimo95** [actiontech/dms#164]
**SQLe Version**
3.2312

**Describe the bug**
SQL工作台审核时，预计使用数据源上应用的规则模板，实际使用了该数据源类型对应的默认规则模板

**To Reproduce**
1. 配置规则模板 mysql_template，禁用规则“禁止使用没有WHERE条件或者WHERE条件恒为TRUE的SQL”
![img_v3_026n_45c4ce84-7b02-43f2-bb65-977dbcc4146g](https://github.com/actiontech/sqle/assets/113898890/be3781aa-72e4-49e0-b4c6-a6a540fb4580)

2. 配置数据源product，配置规则模板为 mysql_template
![image](https://github.com/actiontech/sqle/assets/113898890/a868b45f-da5c-4c7c-9a30-9b0a7ed7bd30)

3. 对该数据源进行SQL审核，没有触发该规则，符合预期
![img_v3_026n_c2ed6ae6-5173-4e45-8509-20e62dedd56g](https://github.com/actiontech/sqle/assets/113898890/23d38335-f6a5-400d-8870-95d68077daa4)

4. 打开SQL工作台，在该数据源上执行相同SQL，触发已禁用的规则，不符合预期
![img_v3_026n_bd616a63-6b81-470d-b262-92884825675g](https://github.com/actiontech/sqle/assets/113898890/40cdea27-7d55-4c2c-b0d9-d5364e1cc3e3)

5. 怀疑是应用了默认规则模板，此时默认规则模板中该规则未被禁用
![image](https://github.com/actiontech/sqle/assets/113898890/e4762318-6fa4-457e-b8d8-72529e0b0d68)

6. 禁用默认规则模板中规则“禁止使用没有WHERE条件或者WHERE条件恒为TRUE的SQL”
7. 再次登陆工作台做审核，没有触发审核规则，符合预期
![image](https://github.com/actiontech/sqle/assets/113898890/974ad39d-013b-46ed-9796-ffea2afcd90a)

**Expected behavior**
SQL工作台审核时，预计使用数据源上应用的规则模板

**Comment by rocky114** [comment]
![image](https://github.com/actiontech/dms/assets/13433110/cc4f7ba4-bf51-4ad3-8f2e-44b45720a146)

![image](https://github.com/actiontech/dms/assets/13433110/e491ae42-0684-4fe1-9cad-15a8435e1b86)

**Comment by iwanghc** [comment]
UI：main a90486ba

### 问题复现
SQLE : main 86bef901
DMS：main 527150c
禁用“禁止使用没有WHERE条件或者WHERE条件恒为TRUE的SQL” 规则
![image](https://github.com/actiontech/dms/assets/83113746/941e0aaa-06c6-4700-b06a-3def2d3df0e4)
选择审核模板
![image](https://github.com/actiontech/dms/assets/83113746/e4c91e2a-e31c-458a-aeca-3d47ef1cac53)
对sql进行审核，没有触发已禁止的规则，符合预期
![image](https://github.com/actiontech/dms/assets/83113746/76add229-4a9d-45da-a1a6-5facbcd3fcaa)
进入cloudbeaver，执行同样的sql，发现触发了已禁用的规则
![image](https://github.com/actiontech/dms/assets/83113746/b8ead6ae-bc7f-4b7b-976d-fe083053f4e1)

### 问题修复验证
SQLE : main d273b93b
DMS：main c7e9210
1、禁用“禁止使用没有WHERE条件或者WHERE条件恒为TRUE的SQL” 规则
2、选择审核模板
3、对sql进行审核，没有触发已禁止的规则，符合预期
4、进入cloudbeaver，执行同样的sql，未触发已禁用的规则，符合预期
![image](https://github.com/actiontech/dms/assets/83113746/1e7ddc86-d5bd-43c9-8a94-4f623ccf47fa)

验证点
模板禁用规则
sql审核禁用规则是否被触发
cloudbeaver执行sql禁用规则是否被触发
