### ISSUE TITLE
项目模糊搜索优化

### ISSUE THREAD

**Issue by ColdWaterLW** [actiontech/dms#165]
## 问题
1. 搜索框里可能搜不到名字完全匹配的项目
2. 搜索结果只有3个，当项目比较多时，无法快速确认搜索的项目是否存在，需要跳转到项目列表确认，那搜索框就起不到快速查找的作用了

## 复现步骤
1. 现有如下项目
![image](https://github.com/actiontech/dms/assets/36940986/20914fec-2d08-4632-86f2-e848f1f5f01c)

3. tes项目搜索不到，这时可能会以为这个项目不存在
![image](https://github.com/actiontech/dms/assets/36940986/df624cb9-1a83-46ea-aeac-c98bcbec30d1)

## 预期
1. 匹配的项目按字符串排序
2. 显示所有匹配的项目（注意：匹配的项目很多时，控制列表框的长度，可以考虑滚动条之类）

**Comment by Gygkimo95** [comment]
已有项目，均已tes开头
![image](https://github.com/actiontech/dms/assets/113898890/7d43a99a-427a-4cad-b6e8-8ec18d5fcfe6)
切换项目时，输入te，可以搜索到所有以te开头的项目名称，无法展示完全的已可用滚动条展示
![image](https://github.com/actiontech/dms/assets/113898890/3944c024-6bef-4738-83d2-225a24d03b34)
