### ISSUE TITLE
增加保存完整三方用户信息

### ISSUE THREAD

**Issue by winfredLIN** [actiontech/dms#166]
https://github.com/actiontech/sqle/issues/2238
### 需求
在用户登录SSO之后，保存从SSO获取到的完整的用户信息

**Comment by winfredLIN** [comment]
### 实现方案

1. 增加保存三方用户信息
2. 增加当使用OAuth2登录时，自动更新三方信息，微信和邮箱

### 需要测试验证的内容

1. 使用Oauth2绑定登录时，用户表中三方用户信息是否保存
2. 使用OAuth2登录时，自动更新三方信息，微信和邮箱

**Comment by taolx0** [comment]
UI: main-ee 09c032e4
DMS: main-ee cf4f2024b2
SQLE: main-ee daee60eff4
![20240201163946](https://github.com/actiontech/dms/assets/63177450/c37b177e-9a5c-4834-b819-d738269bd7c4)
