### ISSUE TITLE
CB登录显示Duplicate valid session cookies:

### ISSUE THREAD

**Issue by LordofAvernus** [actiontech/dms#188]
### 前置要求：【CB和DMS必须在同一个服务器上】
在同一个浏览器中，先使用CB的端口登陆后，在新开页面登陆dms，并执行跳转CB会跳转失败，报错如下
  HTTP ERROR 400 Duplicate valid session cookies: 1k05as6r8w06vacsrjv0syxk5186 ,13xib4111m001jqep2tycym65191
  URI:  /sql_query/
  STATUS: 400
  MESSAGE:  Duplicate valid session cookies: 1k05as6r8w06vacsrjv0syxk5186 ,13xib4111m001jqep2tycym65191
  SERVLET:  -
  CAUSED BY:  org.eclipse.jetty.http.BadMessageException: 400: Duplicate valid session cookies: 1k05as6r8w06vacsrjv0syxk5186 ,13xib4111m001jqep2tycym65191
  Caused by:

## 问题原因：
   dms重转发到CB的过程中，为了修改登录用户，使用了AddCookie方法，该方法会在原有的基础上添加上新的cookie。由于CB页面的【部分】请求会自动带上已有的cookie，会将同一个浏览器其他的CB页面的cookie带入请求头中，导致dms转发的时候存在两个cookie

## 解决方案：
   转发过程中会重置已有的cookie，保证使用预期的cookie

**Comment by iwanghc** [comment]
UI: main a90486ba
SQLE : main 1bf9460b

配置cloudbeaver与dms在同一台服务器
![image](https://github.com/actiontech/dms/assets/83113746/c66b994c-b333-44b4-b2de-1a4c936871aa)
问题复现：
DMS：main 6d781bf
使用cb端口登录
![image](https://github.com/actiontech/dms/assets/83113746/c48f4561-ac46-499d-8aca-50f48ceb643d)
在新开页面登录dms，并进入sql工作台，出现报错
![image](https://github.com/actiontech/dms/assets/83113746/94b29729-1899-4e3e-9c8f-605e8c17882e)

问题修复验证
DMS：main ff4e0d4a68ef27b6b566096a19683af21f4930ae
使用cb端口登录
![image](https://github.com/actiontech/dms/assets/83113746/bba54812-f98d-4cbc-9c19-6923a251b57a)
在新开页面登录dms，并正常进入sql工作台
![image](https://github.com/actiontech/dms/assets/83113746/7fd8250a-e5a7-4a3a-b2f9-eecbf0ea4730)

验证点：
sql工作台登录
