### ISSUE TITLE
dms菜单结构调整

### ISSUE THREAD

**Issue by LZS911** [actiontech/dms#220]
现状：
![image](https://github.com/actiontech/dms/assets/42765421/52f2f320-dd5c-4b36-9419-3bcb704161a7)

预期调整：
![img_v3_029a_39046489-93a0-450f-9081-7c5362f55cdg](https://github.com/actiontech/dms/assets/42765421/dd4dab5a-5a11-43d5-a020-b1c9f5c2444a)

**Comment by iwanghc** [comment]
UI: main a90486ba
DMS ee: main f41f905
SQLE ee: main https://github.com/actiontech/sqle-ee/commit/07d91e04e01c5c43366667d3d93aba3055df5ff4
sqle菜单顺序与结构与issue中预期调整一致
![image](https://github.com/actiontech/dms/assets/83113746/9bf5732e-f20e-47c2-96ee-0a41ac6c4cad)
验证点：
菜单结构
