### ISSUE TITLE
Windows 系统下页面滚动条样式修改

### ISSUE THREAD

**Issue by LZS911** [actiontech/dms#241]
现状：
![image](https://github.com/actiontech/dms/assets/42765421/3cc84acb-b429-4349-afdf-58a2cbfcb255)

预期：
希望能调整下样式，能够更加美观。

**Comment by iwanghc** [comment]
DMS: main ee 9976824
SQLE: main ee 0529703a0

### 问题复现：
UI：main e2d7035
![image](https://github.com/actiontech/dms/assets/83113746/745c6706-b66e-46de-9b20-531ecdab3fdd)

### 问题优化验证：
UI：main 08f7de1a
![image](https://github.com/actiontech/dms/assets/83113746/bc7de630-88e6-4d81-8be3-a769afc0e785)

验证点：
sqle菜单栏滚动条
