### ISSUE TITLE
期望在 http 协议里启用gzip压缩

### ISSUE THREAD

**Issue by Rain-1214** [actiontech/dms#244]
# 背景
预览环境的服务器只有5M的带宽，但是前端由于在线编辑器的缘故，最终前端文件编译产物没有办法打的太小。所以期望能通过开启gzip压缩的方式提升页面的加载速度。
# 方案
echo 原生提供gzip中间件，直接调用即可。
# 影响面
1、理论上因为是中间件，所有会影响所有API。但是http gzip成熟的很。所以理论上不会有什么问题。
2、理论上因为多了压缩的过程，所以会导致进程的cpu占用升高一点点。但是理论上不会升高多少。主观认为，应该不会产生能感知到的升高。
3、由于gzip的压缩原理，所以是有可能出现压缩之后的体积大于压缩之前的体积的。但是这个情况出现的频率应该极低。
# 效果
![image](https://github.com/actiontech/dms/assets/23204067/b91a0f64-b394-46ef-b659-994b63f021fa)
![image](https://github.com/actiontech/dms/assets/23204067/bc23ba69-0572-4207-9552-9124f1c061c6)

**Comment by hasa1K** [comment]
### 版本
dms-ui-ee:ad138d3de45d0ba6b2b0cafc2e7e4da0a7fc3004

### 验证
![image](https://github.com/actiontech/dms/assets/53266479/9512fba2-2736-4c75-90af-be6c1f9d2092)

验证通过
