### ISSUE TITLE
swagger server 优化

### ISSUE THREAD

**Issue by taolx0** [actiontech/dms#269]
# 描述

dms的存在swagger定义不规范的问题

# 优化点

- [x] dms没有区分tag，全部属于dms
- [x] 非GET接口需要调整参数格式
![img_v3_02bu_d4d01ce8-d7ec-4a71-a1b9-135dda16b26g](https://github.com/actiontech/dms/assets/63177450/c8c5328a-e102-4bee-aa4d-ba1233625ca9)

# 解决方案
### 1、dms没有区分tag，全部属于dms
**解决方案**：按照功能以路由名称给dms api分类
**影响**：前端需做出相应调整
### 2、非GET接口需要调整参数格式
**问题原因**：以swagger:route - body形式传参的接口（POST/PATCH/PUT），无法记录body的主体参数名，此问题存在于go-swagger的issue中，并没有给出合理的解决方案,，需再嵌套一层结构体，这会改变我们的接口定义。（[https://github.com/go-swagger/go-swagger/issues/2663]()）
**解决方案**：
 https://goswagger.io/go-swagger/reference/annotations/operation/
使用swagger:operation 描述复杂的端点
**影响**：
- 所有以body传参的接口都做了调整
- 前端需要做出相应的调整
- model中含有path参数的需使用swagger:ignore忽略，若不忽略则会展示到swaggerui上，但不影响接口
- 该调整未修改接口定义，只调整了swagger相关内容，不影响接口调用

### 3、修复其他swagger缺陷
- 注释格式错误
- 路由错误
- Business结构体重复命名导致生成的swagger.json定义不符合预期问题（修改命名，前端同步调整）
- 常量赋值导致生成swagger.json枚举值缺失问题（改为string赋值）

**Comment by iwanghc** [comment]
1、dms没有区分tag，全部属于dms
解决方案：按照功能以路由名称给dms api分类
影响：前端需做出相应调整
2、provision的swag未实现
解决方案：实现获取swagger.yaml接口，提供给dms，可由dms展示
3、非GET接口需要调整参数格式
问题原因：以swagger:route - body形式传参的接口（POST/PATCH/PUT），无法记录body的主体参数名，此问题存在于go-swagger的issue中，并没有给出合理的解决方案,，需再嵌套一层结构体，这会改变我们的接口定义。（[https://github.com/go-swagger/go-swagger/issues/2663]()）
解决方案：
 https://goswagger.io/go-swagger/reference/annotations/operation/
使用swagger:operation 描述复杂的端点
影响：
1、所有以body传参的接口都需要调整
2、前端需要做出相应的调整
3、model中含有path参数的需使用swagger:ignore忽略，若不忽略则会展示到swaggerui上，但不影响接口

**Comment by iwanghc** [comment]
【provision】在swagger ui请求provision接口不通
provision与dms的swagger实现方式类似，原因及修改方式也可参考dms的处理方式
![image](https://github.com/actiontech/dms/assets/83113746/aeb7d0b1-0591-4de4-bf02-112326276eee)

**Comment by taolx0** [comment]
![image](https://github.com/user-attachments/assets/7a2b99f0-529a-446a-9097-c0f5da832f73)
