### ISSUE TITLE
工作台展示实例与项目实例不一致

### ISSUE THREAD

**Issue by LordofAvernus** [actiontech/dms#86]
1. 添加多个数据源后，进入工作台
 2. 移除几个数据源，再次进入工作台，发现工作台的数据源未更新
![image](https://github.com/actiontech/dms/assets/24822803/94d05197-74e8-4024-8b17-ea4fd5f13223)

![image](https://github.com/actiontech/dms/assets/24822803/dae0aded-46ef-4565-bec7-69a863e978b9)

**Comment by taolx0** [comment]
UI: main 743412d8
DMS: main-ee 46df963bc9
SQLE: main-ee 342c635080
![cd-0](https://github.com/actiontech/dms/assets/63177450/a1fd08e4-3398-49b7-bd3f-9f8713c82739)
![cb-1](https://github.com/actiontech/dms/assets/63177450/8873a976-4c91-46ab-9d86-6261300815b1)
